// Mocks generated by Mockito 5.0.16 from annotations
// in ditonton/test/presentation/pages/home_series_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i7;
import 'package:ditonton/bloc/series_list_bloc_cubit.dart' as _i5;
import 'package:ditonton/domain/usecases/get_now_playing_series.dart' as _i3;
import 'package:ditonton/domain/usecases/get_popular_series.dart' as _i2;
import 'package:ditonton/domain/usecases/get_top_rated_series.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetPopularSeries_0 extends _i1.Fake implements _i2.GetPopularSeries {
}

class _FakeGetNowPlayingSeries_1 extends _i1.Fake
    implements _i3.GetNowPlayingSeries {}

class _FakeGetTopRatedSeries_2 extends _i1.Fake
    implements _i4.GetTopRatedSeries {}

class _FakeSeriesListState_3 extends _i1.Fake implements _i5.SeriesListState {}

class _FakeStreamSubscription_4<T> extends _i1.Fake
    implements _i6.StreamSubscription<T> {}

/// A class which mocks [SeriesListBlocCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeriesListBlocCubit extends _i1.Mock
    implements _i5.SeriesListBlocCubit {
  MockSeriesListBlocCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPopularSeries get getPopularSeries =>
      (super.noSuchMethod(Invocation.getter(#getPopularSeries),
          returnValue: _FakeGetPopularSeries_0()) as _i2.GetPopularSeries);
  @override
  _i3.GetNowPlayingSeries get getNowPlayingSeries => (super.noSuchMethod(
      Invocation.getter(#getNowPlayingSeries),
      returnValue: _FakeGetNowPlayingSeries_1()) as _i3.GetNowPlayingSeries);
  @override
  _i4.GetTopRatedSeries get getTopRatedSeries =>
      (super.noSuchMethod(Invocation.getter(#getTopRatedSeries),
          returnValue: _FakeGetTopRatedSeries_2()) as _i4.GetTopRatedSeries);
  @override
  _i5.SeriesListState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeSeriesListState_3()) as _i5.SeriesListState);
  @override
  _i6.Stream<_i5.SeriesListState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i5.SeriesListState>.empty())
          as _i6.Stream<_i5.SeriesListState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i6.Future<void> fetchPopularSeries() =>
      (super.noSuchMethod(Invocation.method(#fetchPopularSeries, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> fetchNowPlayingSeries() =>
      (super.noSuchMethod(Invocation.method(#fetchNowPlayingSeries, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> fetchTopRatedSeries() =>
      (super.noSuchMethod(Invocation.method(#fetchTopRatedSeries, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.StreamSubscription<_i5.SeriesListState> listen(
          void Function(_i5.SeriesListState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_4<_i5.SeriesListState>())
          as _i6.StreamSubscription<_i5.SeriesListState>);
  @override
  void emit(_i5.SeriesListState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i7.Change<_i5.SeriesListState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  String toString() => super.toString();
}
