// Mocks generated by Mockito 5.0.16 from annotations
// in ditonton/test/presentation/pages/series_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;

import 'package:ditonton/bloc/series_detail_bloc_cubit.dart' as _i7;
import 'package:ditonton/domain/entities/series_detail.dart' as _i9;
import 'package:ditonton/domain/usecases/get_series_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_series_recommendations.dart'
    as _i6;
import 'package:ditonton/domain/usecases/get_watchlist_status_series.dart'
    as _i3;
import 'package:ditonton/domain/usecases/remove_watchlist_series.dart' as _i5;
import 'package:ditonton/domain/usecases/save_watchlist_series.dart' as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetSeriesDetail_0 extends _i1.Fake implements _i2.GetSeriesDetail {}

class _FakeGetWatchListStatusSeries_1 extends _i1.Fake
    implements _i3.GetWatchListStatusSeries {}

class _FakeSaveWatchlistSeries_2 extends _i1.Fake
    implements _i4.SaveWatchlistSeries {}

class _FakeRemoveWatchlistSeries_3 extends _i1.Fake
    implements _i5.RemoveWatchlistSeries {}

class _FakeGetSeriesRecommendations_4 extends _i1.Fake
    implements _i6.GetSeriesRecommendations {}

class _FakeSeriesDetailState_5 extends _i1.Fake
    implements _i7.SeriesDetailState {}

class _FakeStreamSubscription_6<T> extends _i1.Fake
    implements _i8.StreamSubscription<T> {}

/// A class which mocks [SeriesDetailBlocCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeriesDetailBlocCubit extends _i1.Mock
    implements _i7.SeriesDetailBlocCubit {
  MockSeriesDetailBlocCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetSeriesDetail get getSeriesDetail =>
      (super.noSuchMethod(Invocation.getter(#getSeriesDetail),
          returnValue: _FakeGetSeriesDetail_0()) as _i2.GetSeriesDetail);
  @override
  _i3.GetWatchListStatusSeries get getWatchListStatusSeries =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatusSeries),
              returnValue: _FakeGetWatchListStatusSeries_1())
          as _i3.GetWatchListStatusSeries);
  @override
  _i4.SaveWatchlistSeries get saveWatchlistSeries => (super.noSuchMethod(
      Invocation.getter(#saveWatchlistSeries),
      returnValue: _FakeSaveWatchlistSeries_2()) as _i4.SaveWatchlistSeries);
  @override
  _i5.RemoveWatchlistSeries get removeWatchlistSeries =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlistSeries),
              returnValue: _FakeRemoveWatchlistSeries_3())
          as _i5.RemoveWatchlistSeries);
  @override
  _i6.GetSeriesRecommendations get getSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getSeriesRecommendations),
              returnValue: _FakeGetSeriesRecommendations_4())
          as _i6.GetSeriesRecommendations);
  @override
  _i7.SeriesDetailState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeSeriesDetailState_5()) as _i7.SeriesDetailState);
  @override
  _i8.Stream<_i7.SeriesDetailState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i7.SeriesDetailState>.empty())
          as _i8.Stream<_i7.SeriesDetailState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i8.Future<void> fetchSeriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchSeriesDetail, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> addWatchlist(_i9.SeriesDetail? seriesDetail) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [seriesDetail]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> deleteWatchlist(_i9.SeriesDetail? seriesDetail) =>
      (super.noSuchMethod(Invocation.method(#deleteWatchlist, [seriesDetail]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> getWatchlistStatus(int? id) =>
      (super.noSuchMethod(Invocation.method(#getWatchlistStatus, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.StreamSubscription<_i7.SeriesDetailState> listen(
          void Function(_i7.SeriesDetailState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_6<_i7.SeriesDetailState>())
          as _i8.StreamSubscription<_i7.SeriesDetailState>);
  @override
  void emit(_i7.SeriesDetailState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i10.Change<_i7.SeriesDetailState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  String toString() => super.toString();
}
